# Rust 拡張モジュール pylopdf_core の型スタブ
class _Document:
    def __init__(self) -> None: ...
    @staticmethod
    def load(path: str) -> _Document: ...
    @staticmethod
    def load_bytes(data: bytes) -> _Document: ...
    @staticmethod
    def load_with_password(path: str, password: str) -> _Document: ...
    @staticmethod
    def load_bytes_with_password(data: bytes, password: str) -> _Document: ...
    def is_encrypted(self) -> bool: ...
    def was_encrypted(self) -> bool: ...
    def set_fallback_font(self, kind: str, data: bytes, index: int) -> None: ...
    def clear_fallback_fonts(self) -> None: ...
    def authenticate_user_password(self, password: str) -> bool: ...
    def authenticate_owner_password(self, password: str) -> bool: ...
    def save(self, path: str) -> None: ...
    def save_bytes(self) -> bytes: ...
    def save_with_object_streams(self, path: str) -> None: ...
    def save_bytes_with_object_streams(self) -> bytes: ...
    def page_count(self) -> int: ...
    def version(self) -> str: ...
    def get_metadata(self) -> dict[str, str]: ...
    def set_metadata(self, key: str, value: str) -> None: ...
    def delete_pages(self, page_numbers: list[int]) -> None: ...
    def select(self, page_numbers: list[int]) -> None: ...
    def extract_text(self, page_numbers: list[int]) -> str: ...
    def merge(self, other: _Document) -> None: ...
    def render_page_png(
        self, page_number: int, scale: float, background: tuple[int, int, int, int] | None
    ) -> bytes: ...
    def render_page_svg(self, page_number: int) -> str: ...
    def compress(self) -> None: ...
    def decompress(self) -> None: ...
    def prune_objects(self) -> None: ...
